name: Build docker

on: workflow_call

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Docker build & Push
        id: docker_build`
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE}}:${{ github.event.number }},${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE}}:latest}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}