name: Cypress Tests

on: pull_request

jobs:
  Build Docker:
    if: job.steps.test.status != failure()
    uses: MXNDEVCND/NMO-admin-client/.github/workflows/buildDocker.yml@v1
    
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress
        uses: cypress-io/github-action@v2
        id: test
        with:
          record: true
          group: merge
          build: npm run build
          start: npm start
          tag: ${{ github.event_name }}
        env:
          CYPRESS_RECORD_KEY:  ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}

      